version: "3"

networks:
  default:
    name: my-custom-network
    external: true

services:
  img2video:
    # command: "sh scripts/run_image2video.sh"
    command: "/bin/bash"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build: .
    volumes:         
          - ./inputs:/usr/src/code/inputs
          - ./results/i2v_512_test:/usr/src/code/newResults
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
