version: "3"

services:
  img2video:
    command: "sh scripts/run_image2video.sh"
    build: .
    volumes:         
          - ./inputs:/usr/src/code/inputs
          - ./results/i2v_512_test:/usr/src/code/newResults



    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

